server:
  port: 8284

spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.3:5432/wbdb?useSSL=false
    username: postgres
    password: 123
    
mybatis:
  mapper-locations:
  - mapper/*.xml
  
  type-aliases-package: com.mcnc.webadmin.models.dtos,com.mcnc.webadmin.models.jwt
  type-handlers-package: com.mcnc.redis.models
  
jwt.key: data key from yml file 
appinfo.message: messageInfo
